### ISSUE TITLE
带上参数的链接会报错

### ISSUE THREAD

**Issue by cluod** [Pudon/weapp-qrcode-base64#1]
如题，带上参数会报错， 
let url ="https://api-jd.sunfax.cn/app/zhanye/article.ashx?id=4138&token=jd_35_510055aeb9b704ab&type=xcx&phone=18366155304"
let imgData = QR.drawImg(
        url ,{
          typeNumber: 4,
          errorCorrectLevel: "M",
          size: 80
        }
      );
这个url地址带参数会报gen is not defined的错误，，但是百度网址什么的就不会报错，

**Comment by pudon** [comment]
已解决=。=
